version: '3.4'

services:
  employee.api:
    image: employee
    build:
      context: .
      dockerfile: src/Employee.API/Dockerfile
    env_file:
      - ./.env
    networks:
      - demogrpchr

  knowledge.api:
    image: knowledge
    build:
      context: .
      dockerfile: src/Knowledge.API/Dockerfile
    networks:
      - demogrpchr

  employeesearchbff.api:
    image: employeesearchbff
    build:
      context: .
      dockerfile: src/EmployeeSearchBff.API/Dockerfile
    networks:
      - demogrpchr

networks:
  demogrpchr:
    name: demogrpchr
    external: true