apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "employeesearchbff.fullname" . }}
  namespace: default
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: {{ include "employeesearchbff.fullname" . }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
          portNumber: {{ .Values.service.port}} # application port
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_json_transcoder
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
            proto_descriptor: "/mnt/descriptor/{{ include "employeesearchbff.fullname" . }}-{{ .Chart.Version }}.pb"
            ignore_unknown_query_parameters: true
            convert_grpc_status: true
            services:
                - "EmployeeSearchBff.SearchGrpcService"
            print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: true
                preserve_proto_field_names: true