# This is a basic workflow to help you get started with Actions

name: EmployeeSearchBff build

on:
  push:
    tags: [ employeesearchbff ]
  pull_request:
    tags: [ employeesearchbff ]

  workflow_dispatch:

jobs:
  build:
    uses: milosslavic/demo-hr/.github/workflows/main.yml@master
    with:
      majorVersion: 1
      buildNumber: ${{ github.run_number }}
      dockerFilePath: src/EmployeeSearchBff.API/Dockerfile
      imageName: employeesearchbff
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.STORAGE_ACCOUNT_CONNECTION}}
