name: Employee build
on:
  push:
    tags: [ employee ]
  pull_request:
    tags: [ employee ]

  workflow_dispatch:

jobs:
  build:
    uses: milosslavic/demo-hr/.github/workflows/main.yml@master
    with:
      majorVersion: 1
      buildNumber: ${{ github.run_number }}
      dockerFilePath: src/Employee.API/Dockerfile
      imageName: employee
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.STORAGE_ACCOUNT_CONNECTION}}
