# This is a basic workflow to help you get started with Actions

name: Knowledge build

on:
  push:
    tags: [ knowledge ]
  pull_request:
    tags: [ knowledge ]

  workflow_dispatch:

jobs:
  build:
    uses: milosslavic/demo-hr/.github/workflows/main.yml@master
    with:
      majorVersion: 1
      buildNumber: ${{ github.run_number }}
      dockerFilePath: src/Knowledge.API/Dockerfile
      imageName: knowledge
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
