name: Base build workflow

on:
 workflow_call:
   inputs:
     majorVersion:
       required: true
       type: number
     buildNumber: #GITHUB_RUN_NUMBER
       required: true
       type: string
     dockerFilePath:
       required: true
       type: string
     imageName:
       required: true
       type: string
   secrets:
     ACR_USERNAME:
       required: true
     ACR_PASSWORD:
       required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Acr url
        env:
          ACR_URL: codetalksacr.azurecr.io
        run: echo $ACR_URL
      - name: Craft image name
        env:
          IMAGE_NAME: ${{ format('{0}/{1}', env.ACR_URL, inputs.imageName) }}
        run: echo $IMAGE_NAME
      - name: Craft version
        env:
          FULL_VER: ${{ inputs.majorVersion }}.${{ inputs.buildNumber }}
        run: echo $FULL_VER
      - uses: docker/login-action@v2
        name: Docker login
        with:
          registry: ${{ env.ACR_URL}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          logout: true
      - uses: docker/build-push-action@v3
        name: Build and push
        with:
          file: ${{ inputs.dockerFilePath }}
          tags: ${{ format('{0}:{1}', env.IMAGE_NAME, env.FULL_VER) }}, ${{ format('{0}:latest', env.IMAGE_NAME) }}
          push: true
          target: final
