name: Proto

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Permissions
        shell: bash
        run: "chmod +x ./tools/protobuild/script.sh"
      - uses: docker://mslavic/proto-gen-descriptor:latest
        name: Build proto descriptor
        with:
          args: "./tools/protobuild/script.sh ./proto employee 1.1 ./"
      - uses: Azure/cli@v1.0.6
        name: Upload file to Azure file share
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{secrets.STORAGE_ACCOUNT_CONNECTION}}
        with:
          inlineScript: |
            az storage file upload --share-name protoshare --source ./descriptor/employee/1.1.pb
