name: Base build workflow

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://mslavic/proto-gen-descriptor:latest
        name: Build proto descriptor
        with:
          #args: "sh -c './tools/protobuild/script.sh ./proto/ ${{ inputs.imageName }} ${{ inputs.majorVersion }}.${{ inputs.buildNumber }} ./'"
          args: "cat ./tools/protobuild/script.sh"
