name: Proto

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Permissions
        shell: bash
        run: "chmod +x ./tools/protobuild/script.sh"
      - uses: docker://mslavic/proto-gen-descriptor:latest
        name: Build proto descriptor
        with:
          args: "sh -c './tools/protobuild/script.sh ./proto/ employee 1.1 ./'"
